# ----------------------------------------
# Created on: Wed Jul 24 19:47:27 2024
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "E:/SoftWare/modelsim/PDS2020.2_sp4.2_lib/usim"
vmap  adc "E:/SoftWare/modelsim/PDS2020.2_sp4.2_lib/adc"
vmap  ddrc "E:/SoftWare/modelsim/PDS2020.2_sp4.2_lib/ddrc"
vmap  ddrphy "E:/SoftWare/modelsim/PDS2020.2_sp4.2_lib/ddrphy"
vmap  hsst_e2 "E:/SoftWare/modelsim/PDS2020.2_sp4.2_lib/hsst_e2"
vmap  iolhr_dft "E:/SoftWare/modelsim/PDS2020.2_sp4.2_lib/iolhr_dft"
vmap  ipal_e1 "E:/SoftWare/modelsim/PDS2020.2_sp4.2_lib/ipal_e1"
vmap  pciegen2 "E:/SoftWare/modelsim/PDS2020.2_sp4.2_lib/pciegen2"
vlog -work work   \
"E:/NEU/FPGA/Learn/Learn_DigitalLogic/4WithHardware/logos/ip_pll/ip_pll/ip_pll.v" \
"E:/NEU/FPGA/Learn/Learn_DigitalLogic/4WithHardware/logos/ip_pll/ip_pll/ipcore/pll_clk/pll_clk.v" \
"E:/NEU/FPGA/Learn/Learn_DigitalLogic/4WithHardware/logos/ip_pll/ip_pll/tb_ip_pll.v" 

# ----------------------------------------
